//////////////////////////////////////////////////////////////////////////
// Copyright (c) 2009 Dynastream Innovations Inc.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
// 
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
//////////////////////////////////////////////////////////////////////////


#if (!REFERENCE_DESIGN)
/*
 * CVS Information - autogenerated - do not modify
 *
 * $Header: /repository/Support_Utilities/ANT_NET/ANT_Managed_Library/ANT_Managed_Library/ANT_ChannelStatus.cs,v 1.4 2009-11-04 18:07:13 canotinoco Exp $
 *
 **************************************************************************
 *
 * To view log use the CVS log command
 */
#endif

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ANT_Managed_Library
{
    /// <summary>
    /// Contains the information returned by a channel status request message
    /// </summary>
    public struct ANT_ChannelStatus
    {
        /// <summary>
        /// Bits 0-1 of the status response
        /// </summary>
        public ANT_ReferenceLibrary.BasicChannelStatusCode BasicStatus;
        /// <summary>
        /// Bits 2-3 of the status response. Invalid on AP1.
        /// </summary>
        public byte networkNumber;
        /// <summary>
        /// Bits 4-7 of the status response. Not a valid channelType on AP1.
        /// </summary>
        public ANT_ReferenceLibrary.ChannelType ChannelType;

        /// <summary>
        /// Creates and fills the ChannelStatus
        /// </summary>
        /// <param name="BasicStatus"></param>
        /// <param name="networkNumber"></param>
        /// <param name="ChannelType"></param>
        public ANT_ChannelStatus(ANT_ReferenceLibrary.BasicChannelStatusCode BasicStatus, byte networkNumber, ANT_ReferenceLibrary.ChannelType ChannelType)
        {
            this.BasicStatus = BasicStatus;
            this.networkNumber = networkNumber;
            this.ChannelType = ChannelType;
        }
    }
}
